import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../models/user_model.dart';
import '../models/subtitle_file.dart';
import '../models/qc_log.dart';
import '../models/attendance.dart';
import '../providers/auth_provider.dart';
import '../providers/data_providers.dart';
import '../themes/app_theme.dart';
import '../widgets/stat_card.dart';
import '../utils/salary_calculator.dart';

class EditorDashboardScreen extends ConsumerWidget {
  final UserModel user;
  const EditorDashboardScreen({super.key, required this.user});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final subtitleFilesAsync = ref.watch(subtitleFilesProvider);
    final attendanceAsync = ref.watch(attendanceProvider);

    return Scaffold(
      appBar: AppBar(
        title: const Text('Editor Dashboard'),
        actions: [
          IconButton(
            icon: const Icon(Icons.logout),
            onPressed: () => ref.read(authNotifierProvider.notifier).logout(),
          ),
        ],
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text('Welcome, ${user.name}', style: Theme.of(context).textTheme.headlineSmall),
            const SizedBox(height: 24),
            attendanceAsync.when(
              data: (attendanceList) {
                final todayAttendance = attendanceList.firstWhere(
                  (att) => att.date.day == DateTime.now().day && att.date.month == DateTime.now().month && att.date.year == DateTime.now().year,
                  orElse: () => Attendance(id: '', userId: user.id, date: DateTime.now(), filesCompleted: 0, attendancePoints: 0, bonusPoints: 0),
                );
                return GridView.count(
                  shrinkWrap: true,
                  physics: const NeverScrollableScrollPhysics(),
                  crossAxisCount: 2,
                  mainAxisSpacing: 16,
                  crossAxisSpacing: 16,
                  children: [
                    StatCard(title: 'Files Completed Today', value: todayAttendance.filesCompleted.toString(), icon: Icons.edit_document, color: Colors.blue),
                    StatCard(title: 'Attendance Points', value: todayAttendance.attendancePoints.toStringAsFixed(1), icon: Icons.check_circle, color: Colors.green),
                    StatCard(title: 'Bonus Points', value: todayAttendance.bonusPoints.toStringAsFixed(1), icon: Icons.star, color: Colors.amber),
                    StatCard(title: 'Salary Estimate', value: '${SalaryCalculator.monthlyFixedSalary.toStringAsFixed(0)} MMK', icon: Icons.money, color: AppTheme.primaryColor),
                  ],
                );
              },
              loading: () => const CircularProgressIndicator(),
              error: (e, st) => Text('Error loading attendance: $e'),
            ),
            const SizedBox(height: 24),
            Text('Assigned Files', style: Theme.of(context).textTheme.titleLarge),
            subtitleFilesAsync.when(
              data: (files) {
                final assignedFiles = files.where((file) => file.assignedEditor == user.id && file.status == FileStatus.assigned).toList();
                if (assignedFiles.isEmpty) {
                  return const Padding(
                    padding: EdgeInsets.all(16.0),
                    child: Text('No files assigned yet.'),
                  );
                }
                return ListView.builder(
                  shrinkWrap: true,
                  physics: const NeverScrollableScrollPhysics(),
                  itemCount: assignedFiles.length,
                  itemBuilder: (context, index) {
                    final file = assignedFiles[index];
                    return Card(
                      margin: const EdgeInsets.symmetric(vertical: 8),
                      child: ListTile(
                        title: Text(file.fileName),
                        subtitle: Text('Status: ${file.status.name}'),
                        trailing: ElevatedButton(
                          onPressed: () {
                            // Simulate file submission
                            ref.read(subtitleFileNotifierProvider.notifier).updateSubtitleFileStatus(file.id, FileStatus.pending);
                            // Update attendance (simplified for now)
                            ref.read(subtitleFileNotifierProvider.notifier).upsertAttendance(
                              Attendance(
                                id: '', // Will be generated by Supabase
                                userId: user.id,
                                date: DateTime.now(),
                                filesCompleted: todayAttendance.filesCompleted + 1,
                                attendancePoints: todayAttendance.attendancePoints + (todayAttendance.filesCompleted + 1 >= SalaryCalculator.dailyTargetFiles ? 5 : 0),
                                bonusPoints: todayAttendance.bonusPoints + (file.totalErrors == 0 ? 0.5 : 0),
                              ),
                            );
                          },
                          child: const Text('Submit'),
                        ),
                      ),
                    );
                  },
                );
              },
              loading: () => const CircularProgressIndicator(),
              error: (e, st) => Text('Error loading files: $e'),
            ),
          ],
        ),
      ),
    );
  }
}
